### ISSUE TITLE
teams settings powershell - wont detect VDI installation

### ISSUE THREAD

**Issue by jkerekes99** [imabdk/PowerShell#1]
I am attempting to use your script in a VDI environment and the script throws message:
VERBOSE: Microsoft Teams application not installed

Teams is installed.
Teams was installed using the MSI installer and the "ALLUSER=1" flag which runs Teams in the per-machine installation mode rather than the per-user mode.

**Comment by imabdk** [comment]
> I am attempting to use your script in a VDI environment and the script throws message:
> VERBOSE: Microsoft Teams application not installed
> 
> Teams is installed.
> Teams was installed using the MSI installer and the "ALLUSER=1" flag which runs Teams in the per-machine installation mode rather than the per-user mode.

Hmm, but even if Teams was installed using the per-machine installation, Teams should install into the user's profile. Do you not have an entry about Teams listed here for each user? "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall"

Also, the script needs to run as the logged on user and not as SYSTEM. I will confirm that even if the per-machine installation is used, once Teams is installed for the logged on user, the script should work :-)

**Comment by jkerekes99** [comment]
No, those entries do not exist for each user.

Machine wide installer places it here:
HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

Yes, I am running in user context.
I am testing running on my admin account manually first before running it via GPO.

I tried to modify your script to include the registry entry above which gets further, but then I get a lot of other errors.

After modifying the check for the registry I get the following errors:

``VERBOSE: Microsoft Teams application not installed
Unable to index into an object of type System.Boolean.
At \\ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:106 char:55
+ $getTeamsDesktopConfigStatus = $getTeamsDesktopConfig[ <<<< 0]
    + CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CannotIndex

Unable to index into an object of type System.Boolean.
At \\ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:107 char:43
+ $teamsConfigPath = $getTeamsDesktopConfig[ <<<< 1]
    + CategoryInfo          : InvalidOperation: (1:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CannotIndex

Unable to index into an object of type System.Boolean.
At \\ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:108 char:48
+ $teamsInstallLocation = $getTeamsDesktopConfig[ <<<< 2]
    + CategoryInfo          : InvalidOperation: (2:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CannotIndex

VERBOSE: Script is done running. Thank you

**Comment by imabdk** [comment]
> No, those entries do not exist for each user.
> 
> Machine wide installer places it here:
> HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
> 
> Yes, I am running in user context.
> I am testing running on my admin account manually first before running it via GPO.
> 
> I tried to modify your script to include the registry entry above which gets further, but then I get a lot of other errors.
> 
> After modifying the check for the registry I get the following errors:
> 
> ``VERBOSE: Microsoft Teams application not installed
> Unable to index into an object of type System.Boolean.
> At \ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:106 char:55
> 
> * $getTeamsDesktopConfigStatus = $getTeamsDesktopConfig[ <<<< 0]
>   
>   * CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
>   * FullyQualifiedErrorId : CannotIndex
> 
> Unable to index into an object of type System.Boolean.
> At \ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:107 char:43
> 
> * $teamsConfigPath = $getTeamsDesktopConfig[ <<<< 1]
>   
>   * CategoryInfo          : InvalidOperation: (1:Int32) [], RuntimeException
>   * FullyQualifiedErrorId : CannotIndex
> 
> Unable to index into an object of type System.Boolean.
> At \ritchies.com.au\sysvol\ritchies.com.au\scripts\configTeams.ps1:108 char:48
> 
> * $teamsInstallLocation = $getTeamsDesktopConfig[ <<<< 2]
>   
>   * CategoryInfo          : InvalidOperation: (2:Int32) [], RuntimeException
>   * FullyQualifiedErrorId : CannotIndex
> 
> VERBOSE: Script is done running. Thank you

Alrighty then. Thank you for those details. 

I will look into enabling the script to cater for that situation. It's really just a check for if Teams is installed. If you're confident that Teams indeed is installed, you could remove those lines of code to work around the issue. In any situation, the relevant .json config file will reside within each user's profile (AppData\Roaming\Microsoft\Teams\desktop-config.json) and that's what's important and how the script will change the Teams settings. :-)

**Comment by imabdk** [comment]
I've been looking into the Teams machine wide installer now, and even when this is used (which btw is the default coming with office now), registry entries are created for each user as Teams is installed for each user. I'm not sure why you don't see this in your end though.
